# -*- coding: utf-8 -*-
"""may23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17JmAXG-Y6RsOTJ0AznYsHfgYTeXAwqNJ
"""

attempt=0
while attempt<3:
    user_name=input("Enter the username: ")
    password =input("Enter the password :")
    if user_name =="Micheal" and password =="e3$WT89x":
            print("You have successfully logged in")
    else:
            attempt+=1
            print("Invalid username or password")
print("Account Locked")

#reading json files

import pandas
from google.colab import drive
drive.mount("/content/gdrive") #this is necessary inorder to import from google drive
path="/content/gdrive/My Drive/Colab Notebooks/supermarkets.json"
data=pandas.read_json(path)
data

#reading excel files

import pandas
from google.colab import drive
drive.mount("/content/gdrive") #this is necessary inorder to import from google drive
path="/content/gdrive/My Drive/Colab Notebooks/supermarkets.xlsx"
data=pandas.read_excel(path,sheet_name=0)
data

#reading text files

import pandas
from google.colab import drive
drive.mount("/content/gdrive") #this is necessary inorder to import from google drive
path="/content/gdrive/My Drive/Colab Notebooks/supermarkets-commas.txt"
data=pandas.read_csv(path)
data

#reading text files

import pandas
from google.colab import drive
drive.mount("/content/gdrive") #this is necessary inorder to import from google drive
path="/content/gdrive/My Drive/Colab Notebooks/supermarkets-semi-colons.txt"
data=pandas.read_csv(path,sep=';')
data