# -*- coding: utf-8 -*-
"""facedetection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aLTv9Wn7KVNNe2euKKv1bUAhhIdK489r
"""

#FACE DETECTION
import cv2
from google.colab.patches import cv2_imshow
face_cascade=cv2.CascadeClassifier("/haarcascade_frontalface_default.xml")
img=cv2.imread("/photo.jpg")
gray_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)#c has to be in caps in cvtColor
faces=face_cascade.detectMultiScale(gray_img,
scaleFactor=1.05,
minNeighbors=5)
print(faces)

for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
cv2_imshow(img)