# -*- coding: utf-8 -*-
"""may30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-QekW92XmVj09t6CbQ-keXnXEusASKC
"""

#INSTALLATION AND GOOGLE COLAB EXAMPLE
!curl -o logo.png https://colab.research.google.com/img/colab_favicon_256px.png
import cv2
img = cv2.imread('logo.png', cv2.IMREAD_UNCHANGED)
cv2_imshow(img)

#GREY SCALE IMAGE
import cv2
from google.colab.patches import cv2_imshow
img=cv2.imread('/galaxy.jpg',0)
print(type(img))#prints the type of image as numpy
print(img)#prints the image
print(img.shape)#gives the no of rows and columns in matrix
print(img.ndim)#gives dimension
cv2_imshow(img)

#COLOUR IMAGE
import cv2
from google.colab.patches import cv2_imshow
img=cv2.imread('/galaxy.jpg',1)
cv2_imshow(img)

#RESIZING THE IMAGE
import cv2
from google.colab.patches import cv2_imshow
img=cv2.imread('/galaxy.jpg',0)
re_im=cv2.resize(img,(100,100))#resizes the image
cv2_imshow(re_im)

#FOR MANY IMAGES
import cv2
import glob
from google.colab.patches import cv2_imshow
images=glob.glob("*.jpg")
for image in images:
    img=cv2.imread(image,0)
    re=cv2.resize(img,(100,100))
    cv2_imshow(re)