# -*- coding: utf-8 -*-
"""mywebsite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DknawyLM0_0SNxip1jBB7XBbYMCgamWL
"""

from flask import Flask
app=Flask(__name__)
@app.route('/')
def home():
    return render_templates("home.html")
@app.route('/about/')
def about():
    return render_templates("about.html")
if __name__=="__main__":
     app.run(debug=True)

!pip install virtualenv