# -*- coding: utf-8 -*-
"""June2_plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O8mNqW1Ghz-oDfmw_pjojJ_Y7i32crM_
"""

from motion_detector import df
from bokeh.plotting import figure, show, output_file
from bokeh.models import HoverTool, ColumnDataSource

df["Start_string"]=df["Start"].dt.strftime("%Y-%m-%d %H:%M:%S")
df["End_string"]=df["End"].dt.strftime("%Y-%m-%d %H:%M:%S")


cds=ColumnDataSource(df)

p=figure(x_axis_type='datetime',height=100, width=500, sizing_mode = "scale_width", title="Motion Graph")
p.yaxis.minor_tick_line_color=None
p.ygrid[0].ticker.desired_num_ticks=1

hover=HoverTool(tooltips=[("Start","@Start_string"),("End","@End_string")])
p.add_tools(hover)

q=p.quad(left="Start",right="End",bottom=0,top=1,color="green",source=cds)

output_file("Graph1.html")
show(p)

#Making a basic Bokeh line graph
 
#importing Bokeh
from bokeh.plotting import figure
from bokeh.io import output_file, show
 
#prepare some data
x=[3,7.5,10]
y=[3,6,9]
 
#prepare the output file
output_file("Line.html")
 
#create a figure object
f=figure()
 
#create line plot
f.triangle(x,y)
 
#write the plot in the figure object
show(f)
#Snippet producing the circle based plot

#Making a basic Bokeh line graph
 
#importing Bokeh
from bokeh.plotting import figure
from bokeh.io import output_file, show
 
#prepare some data
x=[3,7.5,10]
y=[3,6,9]
 
#prepare the output file
output_file("Line.html")
 
#create a figure object
f=figure()
 
#create line plot
f.circle(x,y)
 
#write the plot in the figure object
show(f)

#Plotting percentage of women who received an engineering degree over years
 
#importing bokeh and pandas
from bokeh.plotting import figure
from bokeh.io import output_file, show
import pandas
 
#prepare some data
df=pandas.read_csv("http://pythonhow.com/data/bachelors.csv")
x=df["Year"]
y=df["Engineering"]
 
#prepare the output file
output_file("Line_from_bachelors.html")
 
#create a figure object
f=figure()
 
#create line plot
f.line(x,y)
 
#write the plot in the figure object
show(f)

import pandas
from bokeh.plotting import figure, output_file, show
 
p=figure(plot_width=500,plot_height=400, tools='pan',logo=None)
 
p.title.text="Cool Data"
p.title.text_color="Gray"
p.title.text_font="times"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Date"
p.yaxis.axis_label="Intensity"    
 
p.line([1,2,3],[4,5,6])
output_file("graph.html")
show(p)

#weather
import pandas
 
from bokeh.plotting import figure, output_file, show
 
df=pandas.read_excel("http://pythonhow.com/data/verlegenhuken.xlsx",sheet_name=0)
df["Temperature"]=df["Temperature"]/10
df["Pressure"]=df["Pressure"]/10
 
p=figure(plot_width=500,plot_height=400,tools='pan')
 
p.title.text="Temperature and Air Pressure"
p.title.text_color="Gray"
p.title.text_font="arial"
p.title.text_font_style="bold"
p.xaxis.minor_tick_line_color=None
p.yaxis.minor_tick_line_color=None
p.xaxis.axis_label="Temperature (°C)"
p.yaxis.axis_label="Pressure (hPa)"    
 
p.circle(df["Temperature"],df["Pressure"],size=0.5)
output_file("Weather.html")
show(p)