# -*- coding: utf-8 -*-
"""web.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/128qpKXAm2PvVMaJYDsoj2N6C8rHRR134
"""

import requests
from bs4 import BeautifulSoup
r=requests.get("http://www.pyclass.com/example.html")
c=r.content
c
soup=BeautifulSoup(c,'html.parser')
all=soup.find_all("div",{"class":"cities"})
all